apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mariadb
  namespace: mariadb
  labels:
    type: db
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/mariadb"
