apiVersion: v1
kind: ConfigMap
metadata:
  name: netdata-config
  namespace: monitoring
data:
  netdata.conf: |
    [global]
      run as user = root
    [prometheus:exporter]
      enabled = yes
      data source = as collected
      update every = 10
