apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: databases
  namespace: argocd
spec:
  description: Project for database-related applications
  sourceRepos:
    - https://github.com/samymokhtari/box.infra.git
  destinations:
    - server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: monitoring
  namespace: argocd
spec:
  description: Project for monitoring-related applications
  sourceRepos:
    - https://github.com/samymokhtari/box.infra.git
    - https://sonarsource.github.io/helm-chart-sonarqube
  destinations:
    - server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: Project for application deployments
  sourceRepos:
    - https://github.com/samymokhtari/box.infra.git
  destinations:
    - server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
