version: "3.9"

name: box

services:
  sqlserver:
    container_name: sqlserver
    user: root
    image: azure-sql-edge:latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "rEUommcypCz5UQn"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlserver:/var/opt/mssql/
    networks:
      - net1

  mysql:
    container_name: mysql
    image: mariadb:latest
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_USERNAME: sa
      MARIADB_ROOT_PASSWORD: rEUommcypCz5UQn
    ports:
      - '3306:3306'
    networks:
      - net1

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8888:8080
    networks:
      - net1

networks:
  net1:
    name: net1

volumes:
  sqlserver:
   driver: local
  mysql:
   driver: local