name: private-cloud

services:
  # DATABASES
  azure-sql-edge:
    container_name: azure-sql-edge
    user: root
    restart: always
    image: mcr.microsoft.com/azure-sql-edge:2.0.0 # OR mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    labels:
      backup: "true"
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD} # example: yourStrong(!)Password
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - box_sqlserver:/var/opt/mssql/
      - /backups/mssql:/var/opt/mssql/backups
    networks:
      - net_default

  mariadb:
    container_name: mariadb
    image: mariadb:lts
    restart: always
    volumes:
      - box_mariadb:/var/lib/mysql
    environment:
      MARIADB_USER: ${MARIADB_ROOT_USERNAME}
      MARIADB_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    labels:
      backup: "true"
    ports:
      - "3306:3306"
    networks:
      - net_default

networks:
  net_default:
    name: net_default

volumes:
  box_sqlserver:
    external: true
  box_mariadb:
    external: true
