# docker-compose.yml for any database you want to use on the compute instance "vm-sql"
version: "3.9"

name: box

services:
  azure-sql-edge:
    container_name: azure-sql-edge
    user: root
    image:  mcr.microsoft.com/azure-sql-edge:latest # OR mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      - "MSSQL_SA_PASSWORD=PASSWORD" # example: yourStrong(!)Password
      - "ACCEPT_EULA=Y"
    volumes:
      - sqlserver:/var/opt/mssql/
    networks:
      - net1

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - "MARIADB_ROOT_USERNAME=sa"
      - "MARIADB_ROOT_PASSWORD=PASSWORD"
    ports:
      - '3306:3306'
    networks:
      - net1

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8888:8080
    networks:
      - net1

networks:
  net1:
    name: net1

volumes:
  sqlserver:
   driver: local
  mariadb:
   driver: local