apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-box-files
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/box-files"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-box-files
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual
