apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: azuresql
spec:
  serviceName: "azuresql"
  replicas: 1
  selector:
    matchLabels:
      app: azuresql
  template:
    metadata:
      labels:
        app: azuresql
    spec:
      containers:
        - name: azuresql
          image: mcr.microsoft.com/azure-sql-edge:latest
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: azuresql-secrets
                  key: MSSQL_SA_PASSWORD
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "Developer"
          volumeMounts:
            - name: sql-storage
              mountPath: /var/opt/mssql
  volumeClaimTemplates:
    - metadata:
        name: sql-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
