apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-azuresql
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/data/sqlserver"
