---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mariadb-secrets
  namespace: databases
spec:
  encryptedData:
    DB_PASSWORD: AgCFJMEtE+6LN1uRV42wx5JfJpGOXFzMhlpQYG4RVVDjE4wxqBkapuB/AkKzTUzGzAs1gTZ6sDhtz3jCowFZL+VGSPmUkUusu3eOpO6r7HFsolaiWG/p1DNnS/qEHI6SfLFupCCEVpXhSPRMLOsKISNPNFcbmYT3tvTgUGpQN2vKiBQD3rTLk+wAAJJ94taF7VIVAcaaYtJ9EkieMkPMYgmianx3C3JtaPf6NZ11iCRTR/n7Ydkc5iUQjr3zjPZafbVkLYhGUQ+Yunnmqrvje9aTuWVheUArb9th596Yjsr60eGTRxOx9pRjaPEsn+tX6R28jYzIrn50qHhrTTq3FQCpAcPJfBSfFd945SMDj0h3XBwDW9RyNqkR2c0Z0PFTbEX1c6Jwt1K37RLvrafpzS82WPUGs6vwPnF/frRd6hhQ6jHShfg7qvGyM2wqXoATPUPnqUzs9w8LnGpVftwzRpTaFigf+g6GO8oNp9JcCfQWlTl+n9dQJ0/g210uxtB9hWgqjSYhTVEGCF2EJNBExeiP4HH9niIMmUG1Gk5NAcu4HAM0g8wrw18pXx/hZfIyPopjYuPmkZxupDLmgCRh0Ir2LIKOjVIPipRanlmLuaefZ96BavTQwk4wSGUFXl41UwOYuSZUW1q/b/nqXCj71glA9MOh8hoArZvRzbonWzbkLQcyeiphkCsnc3+RcGDL1xaezCaptgxE3XFf/EXc2FbPPFG5NIOYTj//G1k=
  template:
    metadata:
      creationTimestamp: null
      name: mariadb-secrets
      namespace: databases
    type: Opaque
