apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: databases
  labels:
    type: db
spec:
  type: NodePort # Exposes the service externally
  selector:
    app: mariadb
  ports:
    - protocol: TCP
      port: 3306 # Internal MariaDB port
      targetPort: 3306 # Pod MariaDB port
      nodePort: 32001 # External port (must be between 30000-32767)
