apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: databases
  namespace: argocd
spec:
  project: databases
  destination:
    - server: https://kubernetes.default.svc
      namespace: databases
  sources:
    - repoURL: https://github.com/samymokhtari/box.infra.git
      path: kubernetes/databases/mariadb
      targetRevision: dev
    - repoURL: https://github.com/samymokhtari/box.infra.git
      path: kubernetes/databases/azuresql
      targetRevision: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
spec:
  project: monitoring
  destination:
    - server: https://kubernetes.default.svc
      namespace: monitoring
  sources:
    - repoURL: https://github.com/samymokhtari/box.infra.git
      path: kubernetes/monitoring/grafana
      targetRevision: dev
    - repoURL: https://github.com/samymokhtari/box.infra.git
      path: kubernetes/monitoring/sonar
      targetRevision: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: shared
  destination:
    - server: https://kubernetes.default.svc
      namespace: argocd
  sources:
    - repoURL: https://github.com/samymokhtari/box.infra.git
      path: kubernetes/argocd
      targetRevision: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: letsencrypt
  namespace: argocd
spec:
  project: shared
  destination:
    - server: https://kubernetes.default.svc
      namespace: cert-manager
  sources:
    - repoURL: https://github.com/samymokhtari/box.infra.git
      path: kubernetes/letsencrypt
      targetRevision: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: muslimbot
  namespace: argocd
spec:
  project: apps
  destination:
    - server: https://kubernetes.default.svc
      namespace: apps
  sources:
    - repoURL: https://github.com/samymokhtari/box.infra.git
      path: kubernetes/apps/muslimbot
      targetRevision: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
