apiVersion: v1
kind: Service
metadata:
  name: azuresql
  namespace: databases
  labels:
    type: db
spec:
  type: NodePort # Exposes the service externally
  selector:
    app: azuresql
  ports:
    - protocol: TCP
      port: 1433 # Internal MariaDB port
      targetPort: 1433 # Pod MariaDB port
      nodePort: 32002 # External port (must be between 30000-32767)
