apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: box-api
  namespace: apps
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: box-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300 # Wait 5 minutes before scaling down replicas
      policies:
        - type: Percent
          value: 10 # Do not reduce more than 10% of replicas at once
          periodSeconds: 60
        - type: Pods
          value: 1 # Do not reduce more than 1 Pod at a time
          periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60 # Wait 1 minute before scaling up replicas
      policies:
        - type: Percent
          value: 50 # Add up to 50% more replicas at once
          periodSeconds: 60
        - type: Pods
          value: 2 # Add up to 2 Pods at a time
          periodSeconds: 60
