edition: "developer"

monitoringPasscode: "oZgKrCkpTUe2z2NLx2JQKIw213!"

extraEnv:
  - name: SONAR_ES_BOOTSTRAP_CHECKS_DISABLE
    value: "true"
  - name: SONAR_SEARCH_JAVAADDITIONALOPTS
    value: "-Dnode.store.allow_mmap=false"
  - name: SONAR_JDBC_PASSWORD
    valueFrom:
      secretKeyRef:
        name: sonarqube-secrets
        key: SONAR_JDBC_PASSWORD

persistence:
  enabled: true
  storageClass: ""
  size: 5Gi

postgresql:
  enabled: false # Disable embedded PostgreSQL

jdbcOverwrite:
  enabled: true
  jdbcUrl: "jdbc:sqlserver://azuresql.default.svc.cluster.local:1433;databaseName=sonar;encrypt=false;trustServerCertificate=true"
  jdbcUsername: "sa"
  jdbcSecretName: "sonarqube-secrets"
  jdbcSecretPasswordKey: "SONAR_JDBC_PASSWORD"

sonarQube:
  initialDelaySeconds: 300 # Increase initial delay to accommodate the database start time
  timeoutSeconds: 60
  periodSeconds: 10
  successThreshold: 1
  failureThreshold: 3

  livenessProbe:
    initialDelaySeconds: 360 # Ensure the application has enough time to start
    timeoutSeconds: 60
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3

  startupProbe:
    initialDelaySeconds: 300 # Allow for sufficient startup time
    timeoutSeconds: 60
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
