apiVersion: v1
kind: PersistentVolume
metadata:
  name: muslimbotdev-pv
  labels:
    app: muslimbotdev
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/muslimbotdev"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: muslimbotdev-pvc
  namespace: apps
  labels:
    app: muslimbotdev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
