name: On-Premise CD
on:
  push:
    branches: [on-premise]

env:
  env: "production"
  dockercompose: "docker-compose.yml"
  script_install: "script_install.sh"
  folder: scripts

jobs:
  deploy:
    environment: on-premise
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Set environmental variables"
        run: |
          echo "FULLPATH=/home/${{ secrets.SSH_USERNAME }}/${{ env.folder }}" >> $GITHUB_ENV

      - name: Copy Script Install via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ${{ env.script_install }}
          target: $FULLPATH
          rm: true

      - name: Copy Docker Compose via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ${{ env.dockercompose }}
          target: $FULLPATH
          rm: true

      - name: Give permissions
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            chmod +x $FULLPATH/${{ env.script_install }}
            chmod +x $FULLPATH/${{ env.dockercompose }}

      - name: Setup Machine and Deploy Docker
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            $FULLPATH/${{ env.script_install }}
            echo Starting Docker Compose
            $FULLPATH/${{ env.dockercompose }} up -d \
            -e ENV=${{ env.env }} \
            -e MSSQL_SA_PASSWORD=${{ secrets.DB_PASS }} \
            -e MARIADB_ROOT_USERNAME=${{ secrets.DB_USERNAME }} \
            -e MARIADB_ROOT_PASSWORD=${{ secrets.DB_PASS }} \
            --name box-db 
      