name: On-Premise CD
on:
  push:
    branches: [on-premise]

env:
  env: "production"
  dockercompose: "docker-compose.yml"
  script_install: "script_install.sh"
  folder: scripts

jobs:
  deploy:
    environment: on-premise
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy Script Install via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ${{ env.script_install }}
          target: /home/${{ secrets.SSH_USERNAME }}/${{ env.folder }}
          rm: true

      - name: Copy Docker Compose via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ${{ env.dockercompose }}
          target: /home/${{ secrets.SSH_USERNAME }}/${{ env.folder }}
          rm: true

      - name: Give permissions
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            chmod +x /home/${{ secrets.SSH_USERNAME }}/${{ env.folder }}/${{ env.script_install }}
            chmod +x /home/${{ secrets.SSH_USERNAME }}/${{ env.folder }}/${{ env.dockercompose }}

      - name: Setup Machine
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: /home/${{ secrets.SSH_USERNAME }}/${{ env.script_install }}

      - name: Deploy Docker
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: /home/${{ secrets.SSH_USERNAME }}/${{ env.dockercompose }}
      