name: Continous Deployment
run-name: "Deploy to ${{ github.repo.name }} by @${{ github.actor }}"


on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  env: "production"
  dockercompose: "docker-compose.yml"
  script_install: "script_install.sh"
  backup2gdrive: "backup2gdrive/config.json"

jobs:
  deploy-sources:
    env:
      FULLPATH: /home/${{ secrets.SSH_USERNAME }}/scripts
    environment: on-premise
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy Script Install & Docker compose via ssh
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: ${{ env.script_install }}, ${{ env.dockercompose }}, ${{ env.backup2gdrive }}
          overwrite : true
          target: ${{ env.FULLPATH }}

      - name: Give permissions to execute scripts
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            chmod +x ${{ env.FULLPATH }}/${{ env.script_install }}
            chmod +x ${{ env.FULLPATH }}/${{ env.dockercompose }}
            chmod +rwx ${{ env.FULLPATH }}/backup2gdrive

      - name: Set environments variable in a file .env
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ env.FULLPATH }}
            [ -e .env ] && rm .env
            echo "ENV=${{ env.env }}" >> .env
            echo "MSSQL_SA_PASSWORD=${{ secrets.DB_PASS }}" >> .env
            echo "MARIADB_ROOT_USERNAME=${{ secrets.DB_USER }}" >> .env
            echo "MARIADB_ROOT_PASSWORD=${{ secrets.DB_PASS }}" >> .env
        
      - name: Setup Machine and Deploy Docker Containers
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            ${{ env.FULLPATH }}/${{ env.script_install }}
            echo Starting Docker Compose...
            cd ${{ env.FULLPATH }} 
            docker compose pull
            docker compose up --detach --remove-orphans
      