name: Terraform CD
on:
  push:
    branches: [on-premise]

env:
  env: "production"
  ssh_user: ${{ secrets.SSH_USER }}
  ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      