name: Terraform CI
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [google]
  release:
    types: [published]

env:
    TF_VAR_region: ${{ vars.REGION }}
    TF_VAR_project_id: ${{ vars.PROJECT_ID }}
    TF_VAR_env: "production"
    TF_VAR_ssh_user: ${{ secrets.SSH_USER }}
    TF_VAR_ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
    TF_VAR_gcp_credentials: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
    TF_VAR_conn_str_sql: ${{ secrets.CONN_STR_SQL }}

jobs:
  check-format:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Terraform Format Check
        run: terraform fmt -check -recursive -diff

  validations:
    runs-on: ubuntu-latest
    container: hashicorp/terraform
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
      - name: Terraform Init
        run: terraform init -upgrade
      - name: Terraform Validate
        run: terraform validate
      - name: Terraform Plan (Mock)
        run: terraform plan -lock=false 