name: Terraform CI
on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [on-premise]
  release:
    types: [published]

env:
  env: "production"
  ssh_user: ${{ secrets.SSH_USER }}
  ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
