name: Continous Integration
run-name: "Continous Integration to new changes by @${{ github.actor }}"

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [dev, main]
  release:
    types: [published]

env:
  env: "production"

jobs:
  checks_connectivity:
    environment: on-premise
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test if SSH connection works
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: whoami
