name: Daily Backups
run-name: "Daily backup jobs by @${{ github.actor }} - RUN #${{ github.run_id }}"

on:
   schedule:
      - cron: '0 1 * * *' # Every day at 1 AM
jobs:
   backup-databases:
      env:
         FULLPATH: /home/${{ secrets.SSH_USERNAME }}/scripts
         SCHEDULED_JOBS_PATH: scheduled_jobs
      environment: on-premise
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4

      - name: Set environments variable in a file .env
        uses: appleboy/ssh-action@v1.2.0
        env:
          env: "production"
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ env.FULLPATH }}/${{ env.SCHEDULED_JOBS_PATH }}
            [ -e .env ] && rm .env
            echo "ENV=${{ env.env }}" >> .env
            echo "MSSQL_SA_PASSWORD=${{ secrets.DB_PASS }}" >> .env

      - name: Execute database backups via ssh
        uses: appleboy/ssh-action@v1.2.0
        with:
           host: ${{ secrets.SSH_HOST }}
           username: ${{ secrets.SSH_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: ${{ secrets.SSH_PORT }}
           script: |
            # Navigate to the folder containing scripts
            cd "${{ env.FULLPATH }}/${{ env.SCHEDULED_JOBS_PATH }}" || { echo "Error: Failed to navigate to ${{ env.FULLPATH }}/${{ env.SCHEDULED_JOBS_PATH }}." >&2; exit 1; }

            # List all `.sh` files and loop through each
            errors=0
            for script in backup_*.sh; do
              echo "Executing $script..."
              if ! bash "$script"; then
                echo "Error: Failed to execute $script with exit code $?" >&2
                errors=$((errors + 1))
              fi
            done

            if [ $errors -gt 0 ]; then
              echo "Error: Encountered $errors error(s) during script execution." >&2
              exit 1  # Exit with an error code for GitHub Actions
            else
              echo "Success: All scripts executed successfully."
              exit 0  # Exit with a success code for GitHub Actions
            fi

      - name: Send Backups to Google Drive
        uses: appleboy/ssh-action@v1.2.0
        with:
           host: ${{ secrets.SSH_HOST }}
           username: ${{ secrets.SSH_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: ${{ secrets.SSH_PORT }}
           script: |
            cd ${{ env.FULLPATH }}
            docker compose run --rm backup2gdrive