name: Renew certificates
run-name: Renewing SSL certificates for all domains

on:
   schedule:
      - cron: '0 0 1 * *'
jobs:
   renew-certificates:
      env:
         FULLPATH: /home/${{ secrets.SSH_USERNAME }}/scripts
      environment: on-premise
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4

      - name: Refresh Docker Compose
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            Renewing certificates...
            cd ${{ env.FULLPATH }} 
            sudo docker compose run --rm certbot renew