name: Update docker-compose config
run-name: "Deploy docker-compose to ${{ github.env }} by @${{ github.actor }}"

on:
  workflow_dispatch:

env:
   dockercompose: "docker-compose.yml"


jobs:
   update-docker_compose:
      env:
         FULLPATH: /home/${{ secrets.SSH_USERNAME }}/scripts
      environment: on-premise
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4

      - name: Copy Script Install & Docker compose via ssh
        uses: appleboy/scp-action@v0.1.4
        with:
           host: ${{ secrets.SSH_HOST }}
           username: ${{ secrets.SSH_USERNAME }}
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: ${{ secrets.SSH_PORT }}
           source: ${{ env.dockercompose }}
           overwrite : true
           target: ${{ env.FULLPATH }}

      - name: Refresh Docker Compose
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            Refreshing docker-compose file...
            cd ${{ env.FULLPATH }} 
            sudo docker compose up -d --pull --remove-orphans